import React from 'react'
import './DescriptionBox.css'
const DescriptionBox = () => {
  return (
    <div className="descriptionbox">
        <div className="descriptionbox-navigator">
           <div className="descriptionbox-nav-box">Description</div>
           <div className="descriptionbox-nav-box fade">Reviews (122)</div>
        </div>
        <div className="descriptionbox-description">
            <p>
            An eCommerce website is an online destination where buyers shop for goods and sellers offer products and services. It's the hub of information about a company and what they sell.
            The data generated by an eCommerce website isn't only useful for sellers and buyers. It's also used by shipping and handling providers, 3PL companies, marketers, and warehouse inventory management software.
            eCommerce websites can be created by a specialized agency, web developer, or your own skills. The size and needs of your site play a major part in which choice is best. 
            The terms e-commerce and e-business are often used interchangeably. The term e-tail is also sometimes used in reference to the transactional processes that make up online retail shopping.
            </p>
            <p>
            Ecommerce or electronic commerce refers to a business model that involves sales transactions being done on the web.
             Virtually every online shopping website - big or small - follows this structure. 
            Any site where you can obtain items for sale over the internet is considered an ecommerce website.
            </p>
        </div>
    </div>
  )
}

export default DescriptionBox